apiVersion: batch/v1
kind: CronJob
metadata:
  name: op-4321
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
            containers:
                - name: some-job
                  image: busybox:1.28
                  args: [/bin/sh, -c, 'i=0; while [ "$i" -le "10" ]; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
                  resources:
                      limits:
                          cpu: '250m'
                          memory: '100Mi'
            restartPolicy: OnFailure