apiVersion: apps/v1
kind: Job
metadata:
    name: op-1234
    namespace: astute
spec:
    template:
        spec:
            containers:
                - name: alpine
                  image: alpine:3.16.0
                  command: ['/bin/sh']
                  args: ['-c', 'echo', "I''m a single job"]
                  resources:
                      limits:
                          cpu: '250m'
                          memory: '100Mi'
            restartPolicy: Never
