apiVersion: batch/v1
kind: Job
metadata:
    name: op-1234-4
    namespace: astute
spec:
    ttlSecondsAfterFinished: 360
    template:
        spec:
            containers:
                - name: some_job
                  image: busybox:1.28
                  args: [/bin/sh, -c, 'i=0; while [ "$i" -le "10" ]; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
                  resources:
                      limits:
                          cpu: '250m'
                          memory: '100Mi'
            restartPolicy: Never
